mysite/addons/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.contrib.auth.views import LogoutView

from addons.views import *

app_name = "addons"

urlpatterns = [
    path("", AddonsView.as_view(), name="shop"),
    path("category=<int:category_id>/", AddonsView.as_view(), name="category"),
    path("<str:addon_slug>", AddonPageView.as_view(), name="AddonPage"),
    path("payment-alerts/", payment_alerts, name="payment_alerts"),
    path("successfully/", PaymentSuccess.as_view(), name="payment_success"),
    path("failed/", PaymentFailed.as_view(), name="payment_failed"),
]

mysite/mysite/urls.py
import os

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import include, path, re_path
from django.views.static import serve

from CharPage.views import *
from HomePage.views import *
from talants.views import *
from user.views import *


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", HomePageView.as_view(), name="home"),
    path("user/", include("user.urls", namespace="user")),
    path("support/", include("support.urls", namespace="support")),
    path("addons/", include("addons.urls", namespace="addons")),
    path("services/", include("services.urls", namespace="services")),
    path("char/", CharPageView.as_view(), name="char"),
    path("charlist/", CharListPageView.as_view(), name="char_list"),
    path("createchar/<uuid:room_id>/", CreateCharView.as_view(), name="createchar"),
    path("char/<uuid:room_id>/", UniqueCharPageView.as_view(), name="char_page_room"),
    path("talents/", TalantsView.as_view(), name="talants"),
    path("api/modelviewer/<path:modelviewer_path>/", ZamimgProxyView.as_view(), name="zamimg_proxy"),
    re_path(f"flower/(?P<path>.*)", flower_proxy_view, name="flower"),
    path("__debug__/", include("debug_toolbar.urls")),  # debug toolbar
]

if settings.DEBUG or not os.environ.get("RUN_FROM_DOCKER"):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += [
        re_path(f'^{settings.MEDIA_URL.lstrip("/")}(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),
        re_path(f'^{settings.STATIC_URL.lstrip("/")}(?P<path>.*)$', serve, {"document_root": settings.STATIC_ROOT}),
    ]

handler400 = "HomePage.views.bad_request"
handler403 = "HomePage.views.permission_denied"
handler404 = "HomePage.views.page_not_found"
handler500 = "HomePage.views.server_error"

mysite/services/urls.py
from django.urls import path

from services.views import *

app_name = "services"

urlpatterns = [
    path("", ServicesView.as_view(), name="services"),
    path("success", SuccessAddView.as_view(), name="success_add"),
]

mysite/user/urls.py
from django.urls import path

from user.views import *

app_name = "user"

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("registration/", RegistrationView.as_view(), name="registration"),
    path("terms-of-use/", TermsOfUseView.as_view(), name="terms-of-use"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("profile2/", profileView2, name="profile2"),
    path(
        "confirm-email/<str:uidb64>/<str:token>/<str:email>",
        UserConfirmEmailView.as_view(),
        name="confirm_email",
    ),
    path("email-confirmed/", EmailConfirmedView.as_view(), name="email_confirmed"),
    path(
        "confirm-email-failed/",
        EmailConfirmationFailedView.as_view(),
        name="email_confirmation_failed",
    ),
    path("reset-password/", UserResetPasswordView.as_view(), name="reset_password"),
    path(
        "reset-password2/",
        UserResetPasswordView2.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/<uidb64>/<token>/",
        PasswordResetConfirmCustomView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        PasswordResetCompleteCustomView.as_view(),
        name="password_reset_complete",
    ),
]

mysite/HomePage/views.py
import mimetypes
import uuid

from decouple import config
from django.conf import settings
from django.core.exceptions import BadRequest, PermissionDenied
from django.core.handlers.asgi import ASGIRequest
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import TemplateView
from proxy.views import proxy_view

from HomePage.tasks import send_problem_message

from common.mixin.views import TitleMixin


class HomePageView(TitleMixin, TemplateView):
    """Представление обрабатывающее главную страницу."""

    template_name = "HomePage/HomePage.html"
    title = "Главная страница"

    def get(self, request, *args, **kwargs):
        resp = super().get(request, *args, **kwargs)
        id_class = request.GET.get("class")

        if request.GET.get("data") == "talents":
            return HttpResponse(
                open(
                    f"./static/js/javascript/data-class={id_class}.js",
                    "r",
                    encoding="utf-8",
                ),
                content_type="application/x-javascript; charset=utf-8",
            )

        if request.GET.get("data") == "item-scaling":
            return HttpResponse(
                open(
                    "./static/js/javascript/data-item-scaling.js", "r", encoding="utf-8"
                ),
                content_type="application/x-javascript; charset=utf-8",
            )

        return resp

    def post(self, request: ASGIRequest, *args, **kwargs):
        if self.request.user.is_anonymous:
            return JsonResponse({"status": "access error"})

        if request.FILES:
            # Заполняем словарь нужными данными, так как селери не принимает файлы
            files = {}
            for file in request.FILES:
                files[request.FILES[file].name] = [
                    request.FILES[file].read(),
                    mimetypes.guess_type(request.FILES[file].name)[0],
                ]
        else:
            files = None

        text = request.POST.get("comment", "")

        if files or text != "":
            send_problem_message.delay(files, text)
            return JsonResponse({"status": "complaint sent successfully"})

        return JsonResponse({"status": "complaint not sent"})

    def render_to_response(self, context, **response_kwargs):
        response = super(HomePageView, self).render_to_response(
            context, **response_kwargs
        )

        if self.request.user.is_anonymous:
            if not self.request.COOKIES.get("userID"):
                response.set_cookie(
                    key="userID", value=uuid.uuid4(), domain=settings.PARENT_DOMAIN
                )

        if not self.request.COOKIES.get("ctrEnterWidget"):
            response.set_cookie(
                key="ctrEnterWidget", value="close", domain=settings.PARENT_DOMAIN
            )

        return response


def bad_request(request: ASGIRequest, exception: BadRequest) -> HttpResponse:
    """Обработка ошибки 400"""

    error_msg = "Сервер не смог распознать запрос."
    if type(exception) is BadRequest and str(exception):
        error_msg = str(exception)

    return render(
        request=request,
        template_name="error/error_page.html",
        status=400,
        context={"code": 400, "title": "Неверный запрос", "error_msg": error_msg},
    )


def permission_denied(request: ASGIRequest, exception: BadRequest) -> HttpResponse:
    """Обработка ошибки 403"""

    error_msg = "Доступ к данной странице запрещен."
    if type(exception) is BadRequest and str(exception):
        error_msg = str(exception)

    return render(
        request=request,
        template_name="error/error_page.html",
        status=403,
        context={"code": 403, "title": "Доступ запрещен", "error_msg": error_msg},
    )


def page_not_found(request: ASGIRequest, exception: BadRequest) -> HttpResponse:
    """Обработка ошибки 404"""

    error_msg = "Страница не существует или была перемещена на другой адрес."
    if type(exception) is BadRequest and str(exception):
        error_msg = str(exception)

    return render(
        request=request,
        template_name="error/error_page.html",
        status=404,
        context={"code": 404, "title": "Страница не найдена", "error_msg": error_msg},
    )


def server_error(request: ASGIRequest) -> HttpResponse:
    """Обработка ошибки 500"""

    error_msg = (
        "Cервер столкнулся с неожиданной ошибкой, администрация уже работает над этим."
    )

    return render(
        request=request,
        template_name="error/error_page.html",
        status=500,
        context={"code": 500, "title": "Ошибка сервера", "error_msg": error_msg},
    )


@csrf_exempt
def flower_proxy_view(request: ASGIRequest, path: str) -> HttpResponse:
    """Представление позволяющее открывать панель flower
    как обычную страницу django (только для супер пользователя)."""

    if not request.user.is_superuser:
        raise PermissionDenied
    return proxy_view(
        request,
        f"http://{config('CELERY_FLOWER_ADDRESS')}:{config('CELERY_FLOWER_PORT')}/{config('CELERY_FLOWER_URL_PREFIX')}/{path}",
        {},
    )

mysite/HomePage/templates/HomePage/HomePage.html
{% extends 'base.html' %}
{% load static %}

{% block head %}

{% endblock %}

{% block content %}
<div class="home_page_main">
    <div class="home_page_header">
    <p>Добро пожаловать!</p>
        </div>

    <div class="home_page_info">
        <div>
        <h2>Разделы сайта</h2>
            </div>

        <div>
            <a href="{% url 'char_list' %}"><h3>Персонаж</h3></a>
        </div>

        <p>Во вкладке "Персонаж" вы сможете создавать своего персонажа и кастомизировать его. Изменять расу, пол,
           экипировку.</p>

        <div>
            <a href="{% url 'talants' %}"><h3>Таланты</h3></a>
        </div>

        <p>Во вкладке "Таланты" вы сможете создавать свои пресеты талантов для различных классов и делиться ими.</p>

        <div>
            <a href="{% url 'addons:shop' %}"><h3>Аддоны</h3></a>
        </div>

        <p>Во вкладке "Аддоны" вы сможете приобрести уникальные аддоны для World of Warcraft как для пвп, так и для пве,
           которые вы не найдете в свободном доступе.</p>

        <div>
            <a href="{% url 'services:services' %}"><h3>Услуги</h3></a>
        </div>

        <p>Во вкладке "Услуги" вы сможете записаться на тренировку, бустинг и другие виды услуг.</p>
    </div>
</div>

<!--<a href="@">-->
<!--<div class="light-button">-->
<!--    <button class="bt">-->
<!--        <div class="light-holder">-->
<!--            <div class="dot"></div>-->

<!--            <div class="light"></div>-->
<!--        </div>-->
<!--        <div class="button-holder">-->
<!--            <svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">-->
<!--                <path d="M20.317 4.3698a19.7913 19.7913 0 00-4.8851-1.5152.0741.0741 0 00-.0785.0371c-.211.3753-.4447.8648-.6083 1.2495-1.8447-.2762-3.68-.2762-5.4868 0-.1636-.3933-.4058-.8742-.6177-1.2495a.077.077 0 00-.0785-.037 19.7363 19.7363 0 00-4.8852 1.515.0699.0699 0 00-.0321.0277C.5334 9.0458-.319 13.5799.0992 18.0578a.0824.0824 0 00.0312.0561c2.0528 1.5076 4.0413 2.4228 5.9929 3.0294a.0777.0777 0 00.0842-.0276c.4616-.6304.8731-1.2952 1.226-1.9942a.076.076 0 00-.0416-.1057c-.6528-.2476-1.2743-.5495-1.8722-.8923a.077.077 0 01-.0076-.1277c.1258-.0943.2517-.1923.3718-.2914a.0743.0743 0 01.0776-.0105c3.9278 1.7933 8.18 1.7933 12.0614 0a.0739.0739 0 01.0785.0095c.1202.099.246.1981.3728.2924a.077.077 0 01-.0066.1276 12.2986 12.2986 0 01-1.873.8914.0766.0766 0 00-.0407.1067c.3604.698.7719 1.3628 1.225 1.9932a.076.076 0 00.0842.0286c1.961-.6067 3.9495-1.5219 6.0023-3.0294a.077.077 0 00.0313-.0552c.5004-5.177-.8382-9.6739-3.5485-13.6604a.061.061 0 00-.0312-.0286zM8.02 15.3312c-1.1825 0-2.1569-1.0857-2.1569-2.419 0-1.3332.9555-2.4189 2.157-2.4189 1.2108 0 2.1757 1.0952 2.1568 2.419 0 1.3332-.9555 2.4189-2.1569 2.4189zm7.9748 0c-1.1825 0-2.1569-1.0857-2.1569-2.419 0-1.3332.9554-2.4189 2.1569-2.4189 1.2108 0 2.1757 1.0952 2.1568 2.419 0 1.3332-.946 2.4189-2.1568 2.4189Z"></path>-->
<!--            </svg>-->

<!--            <p>Discord</p>-->
<!--        </div>-->
<!--    </button>-->

<!--</div>-->
<!--    </a>-->


{% endblock %}

{% block js %}

{% endblock %}