mysite/addons/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.contrib.auth.views import LogoutView

from addons.views import *

app_name = "addons"

urlpatterns = [
    path("", AddonsView.as_view(), name="shop"),
    path("category=<int:category_id>/", AddonsView.as_view(), name="category"),
    path("<str:addon_slug>", AddonPageView.as_view(), name="AddonPage"),
    path("payment-alerts/", payment_alerts, name="payment_alerts"),
    path("successfully/", PaymentSuccess.as_view(), name="payment_success"),
    path("failed/", PaymentFailed.as_view(), name="payment_failed"),
]

mysite/mysite/urls.py
import os

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import include, path, re_path
from django.views.static import serve

from CharPage.views import *
from HomePage.views import *
from talants.views import *
from user.views import *


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", HomePageView.as_view(), name="home"),
    path("user/", include("user.urls", namespace="user")),
    path("support/", include("support.urls", namespace="support")),
    path("addons/", include("addons.urls", namespace="addons")),
    path("services/", include("services.urls", namespace="services")),
    path("char/", CharPageView.as_view(), name="char"),
    path("charlist/", CharListPageView.as_view(), name="char_list"),
    path("createchar/<uuid:room_id>/", CreateCharView.as_view(), name="createchar"),
    path("char/<uuid:room_id>/", UniqueCharPageView.as_view(), name="char_page_room"),
    path("talents/", TalantsView.as_view(), name="talants"),
    path("api/modelviewer/<path:modelviewer_path>/", ZamimgProxyView.as_view(), name="zamimg_proxy"),
    re_path(f"flower/(?P<path>.*)", flower_proxy_view, name="flower"),
    path("__debug__/", include("debug_toolbar.urls")),  # debug toolbar
]

if settings.DEBUG or not os.environ.get("RUN_FROM_DOCKER"):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += [
        re_path(f'^{settings.MEDIA_URL.lstrip("/")}(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),
        re_path(f'^{settings.STATIC_URL.lstrip("/")}(?P<path>.*)$', serve, {"document_root": settings.STATIC_ROOT}),
    ]

handler400 = "HomePage.views.bad_request"
handler403 = "HomePage.views.permission_denied"
handler404 = "HomePage.views.page_not_found"
handler500 = "HomePage.views.server_error"

mysite/support/urls.py
from django.urls import path

from support.views import *

app_name = "support"

urlpatterns = [
    path("chat/", SupportChatView.as_view(), name="chat"),
    path("admin-chat/", AdminSupportChatView.as_view(), name="admin-chat"),
]

mysite/user/urls.py
from django.urls import path

from user.views import *

app_name = "user"

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("registration/", RegistrationView.as_view(), name="registration"),
    path("terms-of-use/", TermsOfUseView.as_view(), name="terms-of-use"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("profile2/", profileView2, name="profile2"),
    path(
        "confirm-email/<str:uidb64>/<str:token>/<str:email>",
        UserConfirmEmailView.as_view(),
        name="confirm_email",
    ),
    path("email-confirmed/", EmailConfirmedView.as_view(), name="email_confirmed"),
    path(
        "confirm-email-failed/",
        EmailConfirmationFailedView.as_view(),
        name="email_confirmation_failed",
    ),
    path("reset-password/", UserResetPasswordView.as_view(), name="reset_password"),
    path(
        "reset-password2/",
        UserResetPasswordView2.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/<uidb64>/<token>/",
        PasswordResetConfirmCustomView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        PasswordResetCompleteCustomView.as_view(),
        name="password_reset_complete",
    ),
]

mysite/addons/models.py
from django.db import models

from user.models import User


# Create your models here.


class AddonCategory(models.Model):
    name = models.CharField(max_length=128, unique=True)
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Compatible_Versions(models.Model):
    version = models.CharField("Версия игры", max_length=32)

    def __str__(self):
        return self.version


class Addon(models.Model):
    name = models.CharField(max_length=256, verbose_name="Название аддона")
    description = models.CharField(verbose_name="Краткое описание аддона")
    full_description = models.TextField(verbose_name="Полное описание аддона")
    category = models.ManyToManyField(
        AddonCategory, related_name="a_category", verbose_name="Категория"
    )

    author = models.CharField(default="Jojin", max_length=32, verbose_name="Автор")
    version = models.ManyToManyField(Compatible_Versions, verbose_name="Версия игры:")
    file = models.FileField(
        upload_to="addons_file", null=True, verbose_name="Файл с аддоном"
    )
    preview = models.ImageField(
        upload_to="addons_images/preview", verbose_name="Картинка карточки аддона"
    )

    price = models.DecimalField(max_digits=6, decimal_places=0, verbose_name="Цена")

    slug = models.SlugField(
        max_length=255, unique=True, db_index=True, verbose_name="Слаг", default=""
    )

    is_published = models.BooleanField(default=False, verbose_name="Публикация")

    def __str__(self):
        return f"Аддон: {self.name} | Категория: {self.category.name}"


class AddonImage(models.Model):
    image = models.ImageField(upload_to="addons_images", verbose_name="Картинка аддона")
    addon = models.ForeignKey(Addon, on_delete=models.CASCADE, related_name="images")


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Покупатель")
    addon = models.ForeignKey(Addon, on_delete=models.CASCADE, verbose_name="Аддон")
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата создания заказа"
    )
    status = models.BooleanField(default=False, verbose_name="Заказ оплачен?")

    def __str__(self):
        return f"Заказ {self.id}"

mysite/addons/views.py
import hashlib

from django.conf import settings
from django.core.cache import cache
from django.db.models import Count
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.views.generic.list import ListView

from addons.models import Addon, AddonCategory, Order
from common.mixin.views import TitleMixin


# Create your views here.


class AddonsView(TitleMixin, ListView):
    """Представление обрабатывающее страницу товаров с аддонами."""

    model = Addon
    template_name = "addons/addons_shop.html"
    title = "Магазин аддонов"

    # paginate_by = 4
    def get_queryset(self):
        queryset = super(AddonsView, self).get_queryset()
        category_id = self.kwargs.get("category_id")
        if category_id:
            cache.clear()

        filter = self.request.GET.get("filter")

        if filter:
            list_filter = {"price": "price", "-price": "-price", "popular": "name"}

            return (
                queryset.filter(category__id=category_id, is_published=True).order_by(list_filter.get(filter, ""))
                if category_id
                else queryset.filter(is_published=True).order_by(list_filter.get(filter, ""))
            )
        else:
            return (
                queryset.filter(category__id=category_id, is_published=True)
                if category_id
                else queryset.filter(is_published=True)
            )

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(AddonsView, self).get_context_data()

        user = self.request.user

        if user.is_authenticated:
            context["paid_addons"] = Addon.objects.filter(order__user=user, order__status=True)

        categories = cache.get("categories")

        if not categories:
            # возвращаем только те категории, которые используются
            context["categories"] = AddonCategory.objects.annotate(one=Count("a_category")).filter(one__gt=0)
            cache.set("categories", context["categories"], 30)
        else:
            context["categories"] = categories
        return context


class AddonPageView(TemplateView):
    """Представление обрабатывающее страницу товара(аддона)."""

    template_name = "addons/addon_page.html"

    def get_context_data(self, **kwargs):
        context = super(AddonPageView, self).get_context_data()

        context["addon"] = Addon.objects.filter(slug=kwargs["addon_slug"])[0]

        user = self.request.user
        if user.is_authenticated:
            context["paid"] = Order.objects.filter(user=user, addon=context["addon"], status=True).exists()

        context["title"] = context["addon"].name

        if self.request.user.is_authenticated:
            currency = "RUB"
            order = Order.objects.create(user=self.request.user, addon=context["addon"])
            sign = hashlib.md5(
                f'{settings.MERCHANT_ID}:{context["addon"].price}:{settings.SECRET_WORD}:{currency}:{order.id}'.encode(
                    "utf-8"
                )
            ).hexdigest()
            context["payment_url"] = (
                f'https://pay.kassa.shop/?m={settings.MERCHANT_ID}&oa={context["addon"].price}&s={sign}&currency={currency}&o={order.id}'
            )

        return context


def payment_alerts(request):
    if request.GET.get("MERCHANT_ID") == settings.MERCHANT_ID:
        order = Order.objects.get(id=request.GET.get("MERCHANT_ORDER_ID"))

        amount = request.GET.get("AMOUNT")

        if order.addon.price == int(amount):
            order.status = True

            order.save()

        return HttpResponse("YES")

    else:
        return HttpResponse("NO")


class PaymentSuccess(TitleMixin, TemplateView):
    template_name = "addons/payment_success.html"
    title = "Успех!"


class PaymentFailed(TitleMixin, TemplateView):
    template_name = "addons/payment_failed.html"
    title = "Неудача!"

mysite/addons/templates/addons/addon_page.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<script src="{% static 'js/javascript/zamimg_power.min.js' %}"></script>
<script>const wowhead_tooltips = { "colorlinks": true, "iconizelinks": true, "iconSize": "small",  "renamelinks": false }</script>
{% endblock %}

{% block content %}

<div class="addon_page_main">
    {{ addon.full_description|safe }}
<div class="slider-main">
    <div class="slider-container">
        <div class="slider">
            {% for image in addon.images.all %}
                <img src="{{ image.image.url }}" alt="" width="186" height="100">
            {% endfor %}
        </div>
        <button class="prev-button" aria-label="Посмотреть предыдущий слайд">&lt;</button>
        <button class="next-button" aria-label="Посмотреть следующий слайд">&gt</button>
      </div>
</div>

    <div class="addon_info_panel">

        <div  class="addon_page_name">
            <p>{{ addon.name }}</p>
        </div>

        <p class="addon_page_price" style="font-size: 24px;">{{ addon.price }}р.</p>

        <p class="addon_page_author">Автор: {{ addon.author }}</p>

        <p class="addon_page_sovm">Совместимость: 3.3.5, 3.4.0</p>
        {% if paid %}
        <a href="{% url 'user:profile' %}">
            <div class="addon-page-buy-btn">
                <p>Перейти к моим аддонам</p>
            </div>
        </a>
        {% else %}
        <a href="@">
            <div class="addon-page-buy-btn">
                <p>Купить</p>
            </div>
        </a>
        {% endif %}



    </div>

    </div>
{% endblock %}

{% block js %}
<script>
// Получаем элементы слайдера
const slider = document.querySelector('.slider');
const prevButton = document.querySelector('.prev-button');
const nextButton = document.querySelector('.next-button');
const slides = Array.from(slider.querySelectorAll('img'));
const slideCount = slides.length;
let slideIndex = 0;

// Устанавливаем обработчики событий для кнопок
prevButton.addEventListener('click', showPreviousSlide);
nextButton.addEventListener('click', showNextSlide);

// Функция для показа предыдущего слайда
function showPreviousSlide() {
  slideIndex = (slideIndex - 1 + slideCount) % slideCount;
  updateSlider();
}

// Функция для показа следующего слайда
function showNextSlide() {
  slideIndex = (slideIndex + 1) % slideCount;
  updateSlider();
}

// Функция для обновления отображения слайдера
function updateSlider() {
  slides.forEach((slide, index) => {
    if (index === slideIndex) {
      slide.style.display = 'block';
    } else {
      slide.style.display = 'none';
    }
  });
}

// Инициализация слайдера
updateSlider();
</script>
{% endblock %}

mysite/addons/templates/addons/addons_shop.html
{% extends 'base.html' %}
{% load static %}
{% load cache %}

{% block content %}
<div class="addons_shop">

    <div class="addons_category">

        <div class="category_header">

            <p>Категория</p>

        </div>

        <div class="category_list">
            {% for category in categories %}
            <div class="category">

                <a href="{%  url 'addons:category' category.id %}">
                    <p>{{ category.name }}</p>
                </a>

            </div>
            {% endfor %}

            <a href="{% url 'addons:shop' %}">

                <div class="reset-category-btn">

                    <p>Сбросить категорию</p>

                </div>
            </a>

        </div>

    </div>

    <div class="addons_main" style="width: 100%;">

        <div class="addons_services">

        <div class="addons_filter" id="addons_filter">

            <p>Фильтры</p>
            <img src="{% static 'img/other/white_triangle.png' %}" width="17" height="17" id="tringle">



        </div>

            <div class="addon_filter_open" id="addon_filter_open" open="False">
                <div id="filter_popular"><a href="{{ request.path }}?filter=popular">Популярное</a></div>
                <div id="filter_price"><a href="{{ request.path }}?filter=price">Дешевле</a></div>
                <div id="filter_-price"><a href="{{ request.path }}?filter=-price">Дороже</a></div>
            </div>

        <div class="addons-search">

             <div class="seacrh-item" id="search-item">


                <div class="seacrh-input" id="seacrh-input" style="margin-right: 0px;">

                    <p id="placeholder-search">Поиск</p>
                    <input id="input-item-id">

                </div>


            </div>

        </div>

    </div>

        <div class="addons_cards">


            {% for product in object_list %}
                <div class="addon">

                <img src="{{ product.preview.url }}" alt="" width="186" height="100">
                <p class="addon_name">{{ product.name }}</p>
                <p class="addon_description">{{ product.description }}</p>
                <p class="addon_price">{{ product.price }}р.</p>
                    {% if user.is_authenticated %}
                        {% if product in paid_addons %}
                            <div class="addon_paid">
                                <a href="{% url 'user:profile' %}">
                                    <div class="user_profile">
                                        <img src="{% static 'img/other/user_icon.png' %}">
                                    </div>
                                </a>
                                <a href="{% url 'addons:shop' %}{{ product.slug }}">

                                    <div class="more_details_addon">

                                        <p>Подробнее</p>

                                    </div>
                                </a>
                            </div>
                        {% else %}
                            <a href="{% url 'addons:shop' %}{{ product.slug }}">

                    <div class="buy-btn">

                        <p>Купить</p>

                    </div>
                </a>
                        {% endif %}
                    {% else %}
                        <a href="{% url 'addons:shop' %}{{ product.slug }}">

                    <div class="buy-btn">

                        <p>Купить</p>

                    </div>
                </a>
                    {% endif %}
            </div>
            {% endfor %}




        </div>





        <div class="container-pag">
  <ul class="pagination" onclick="show_item(event)">



  </ul>
</div>

    </div>
</div>
{% endblock %}

{% block js %}
<script>

// addon_filter_open...............................................................................................

    function set_value(){
        const urlParams = new URLSearchParams(window.location.search);
        const myParam = urlParams.get('filter');
        if(myParam){
        var list_filter = {'price': 'Дешевле', '-price': 'Дороже', "popular": "Популярное"}
        document.getElementById("addons_filter").firstElementChild.innerText = list_filter[myParam];
        };

    };

    window.onload = set_value;
//..................................

    // input anim...............................................................................................

        function inputcheck(textid, input) {
            var text = document.getElementById(`${textid}`);
            let coords = {top: text.offsetTop, left: text.offsetLeft};
            console.log(coords);

            var top = text.offsetTop;
            var left = text.offsetLeft;

            console.log(text.offsetLeft, text.offsetTop);
            var fsize = 15;
            if(window.getComputedStyle(text, null).fontSize == fsize + "px"){

            var topy = setInterval(topfunc, 10);
            var leftx = setInterval(leftfunc, 23);
            var fsizex = setInterval(fsizefunc, 23);
            function topfunc() {
                var direction = 1;
                if(top == coords.top - 19) {
                    clearInterval(topy);
                }else {
                    console.log(1);
                    top -= 1 * direction;
                    text.style.top = top + "px";
                }
                }

            function leftfunc() {
                var direction = 1;
                if(left == coords.left - 5) {
                    clearInterval(leftx);
                }else {
                     left -= 1 * direction;
                    text.style.left = left + "px";
                }
                }

            function fsizefunc() {
                var bttn = document.getElementById(`${input}`);
                var direction = 1;
                if(fsize == 10) {
                    bttn.disabled = false;
                    clearInterval(fsizex);
                }else {
                    fsize -= 1 * direction;
                    text.style.fontSize = fsize + "px";
                }
                }
                }
        }

        function inputout(idtext, input) {
            var text = document.getElementById(`${idtext}`);

            //console.log(document.getElementById(`${input}`).value) //--- чтение из инпута
            if(document.getElementById(`${input}`).value == ""){

            let coords = {top: text.offsetTop, left: text.offsetLeft};
            //console.log(coords);

            var top = text.offsetTop;
            var left = text.offsetLeft;

            //console.log(text.offsetLeft, text.offsetTop);
            var fsize = 10;
            if(window.getComputedStyle(text, null).fontSize == fsize + "px"){


            var topy = setInterval(topfunc, 10);
            var leftx = setInterval(leftfunc, 23);
            var fsizex = setInterval(fsizefunc, 25);

                function topfunc() {
                    var direction = -1;
                    if(top == coords.top + 19) {
                        clearInterval(topy);
                    }else {
                        top -= 1 * direction;
                        text.style.top = top + "px";
                    }
                    }

                function leftfunc() {
                    var direction = -1;
                    if(left == coords.left + 5) {
                        clearInterval(leftx);
                    }else {
                         left -= 1 * direction;
                        text.style.left = left + "px";
                    }
                    }

                function fsizefunc() {
                    var bttn = document.getElementById(`${input}`);
                    var direction = -1;
                    if(fsize == 15) {
                        bttn.disabled = false;
                        clearInterval(fsizex);
                    }else {
                        bttn.disabled = true;
                        fsize -= 1 * direction;
                        text.style.fontSize = fsize + "px";
                    }
                    }
                    }
            }


        }

        // вызов функции на нажатие инпут
        document.getElementById("input-item-id").addEventListener('mousedown', inputcheck.bind(null, "placeholder-search", "input-item-id"));

        // вызов функции при ухода из инпута
        document.getElementById("input-item-id").addEventListener('focusout', inputout.bind(null, "placeholder-search", "input-item-id"));

//..........................

// addon_filter_open...............................................................................................

    function rotate_tringle(d){
        var d= d;
        if(d == 0){
            var rotate_interval = setInterval(function w(){
            if(d == 180){
                clearInterval(rotate_interval);
            };
            document.getElementById("tringle").style['-webkit-transform']= `rotate(${d + "deg"})`;
            d +=3;
            },4);
        };

        if(d == 180){
            var rotate_interval = setInterval(function w(){
            if(d == 360){
                clearInterval(rotate_interval);
            }
            document.getElementById("tringle").style['-webkit-transform']= `rotate(${d + "deg"})`;
            d +=3;
            },4);
        };
    };

    function addon_filter_open() {
        //var obj = document.getElementById("addon_filter_open");
        var obj = document.querySelector(".addon_filter_open");
        var attr = obj.getAttribute("open")
        if(attr == "False"){
            rotate_tringle(0);
            obj.setAttribute("open", "True")
            obj.style.display = "block"

        }

        if(attr == "True"){
            rotate_tringle(180);
            obj.setAttribute("open", "False")
            obj.style.display = "none"

        }

        console.log(obj.getAttribute("open"))
    }



     document.getElementById("addons_filter").addEventListener('mousedown', addon_filter_open);

//..................................

// search...............................................................................................

//input_id = input-item-id


    document.querySelector('#input-item-id').oninput = function () {

        var val = this.value.toLowerCase().trim();
        var obj_list = document.querySelectorAll('.addons_cards div');
        console.log(obj_list)
        if (val != '') {

            obj_list.forEach(function (elem) {

                if(elem.getAttribute("class") == 'addon' || elem.getAttribute("class") == 'addon hide'){

                    if (elem.innerText.toLowerCase().search(val) == -1){

                        elem.classList.add('hide');
                        elem.style.display = 'none'

                    }
                    else {
                        elem.classList.remove('hide');
                        elem.style.display = 'block'
                    }
                }
            });
        }
        else {
            paginator()
            obj_list.forEach(function (elem) {
                elem.classList.remove('hide');
            });
        }
    }

//..................................

// paginator..........................


var page_size = 8; //сколько отображаем сначала
var count_page = Math.ceil(count / page_size); //кол-во страниц
var count = document.querySelectorAll('.addon').length; //всего записей
var list_obj = document.querySelectorAll('.addon')

function paginator(){
    list_obj.forEach(function (elem) {
                elem.style.display = 'none';
            });
    var count_page = Math.ceil(count / page_size); //кол-во страниц

    var paginator = document.querySelector(".pagination");
    var page = "";
    for (var i = 0; i < count_page; i++) {
      page += "<li><p>" + (i+1) + "</p></li>";
    }
    paginator.innerHTML = page;

     for(var i = 0; i < 1 * page_size; i++){
            console.log(i)
            if (list_obj[i]){
                list_obj[i].style.display = 'block'
            }
        }

    var buttuns_p = document.querySelectorAll(".pagination p");
    console.log(buttuns_p)
    buttuns_p[0].classList.add("active");
}
//..
function show_item(event){
    var buttuns_p = document.querySelectorAll(".pagination p");
    var e = event || window.event;
    var target = e.target;
    buttuns_p.forEach(function (elem) {
                console.log(1)
                elem.classList.remove("active");
            });
    target.classList.add("active");
    var page = target.innerText;


    list_obj.forEach(function (elem) {
                console.log(1)
                elem.style.display = 'none';
            });
    for(var i = (page-1) * page_size; i < page * page_size; i++){
        console.log(i)
        if (list_obj[i]){
            list_obj[i].style.display = 'block'
        }
    }
}

window.onload = paginator;
//...................

</script>
{% endblock %}

mysite/addons/templates/addons/payment_failed.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'email-confirmed.css' %}">
{% endblock %}

{% block content %}
<div class="confirmed_email">
    <p>Что-то пошло не так!<br/>За дополнительной информацией обратитесь в <a href="{% url 'support:chat' %}" style="color: #007bff;">Техническую поддержку</a></p>
</div>
{% endblock %}

mysite/addons/templates/addons/payment_success.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'email-confirmed.css' %}">
{% endblock %}

{% block content %}
<div class="confirmed_email">
    <p>Благодарим за покупку!</p><br/><p style="font-weight: 400;">Купленный аддон можно скачать на странице <a href="{% url 'user:profile' %}" style="color: #007bff;">Личного кабинета</a>!</p>
</div>
{% endblock %}