mysite/addons/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.contrib.auth.views import LogoutView

from addons.views import *

app_name = "addons"

urlpatterns = [
    path("", AddonsView.as_view(), name="shop"),
    path("category=<int:category_id>/", AddonsView.as_view(), name="category"),
    path("<str:addon_slug>", AddonPageView.as_view(), name="AddonPage"),
    path("payment-alerts/", payment_alerts, name="payment_alerts"),
    path("successfully/", PaymentSuccess.as_view(), name="payment_success"),
    path("failed/", PaymentFailed.as_view(), name="payment_failed"),
]

mysite/mysite/urls.py
import os

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import include, path, re_path
from django.views.static import serve

from CharPage.views import *
from HomePage.views import *
from talants.views import *
from user.views import *


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", HomePageView.as_view(), name="home"),
    path("user/", include("user.urls", namespace="user")),
    path("support/", include("support.urls", namespace="support")),
    path("addons/", include("addons.urls", namespace="addons")),
    path("services/", include("services.urls", namespace="services")),
    path("char/", CharPageView.as_view(), name="char"),
    path("charlist/", CharListPageView.as_view(), name="char_list"),
    path("createchar/<uuid:room_id>/", CreateCharView.as_view(), name="createchar"),
    path("char/<uuid:room_id>/", UniqueCharPageView.as_view(), name="char_page_room"),
    path("talents/", TalantsView.as_view(), name="talants"),
    path("api/modelviewer/<path:modelviewer_path>/", ZamimgProxyView.as_view(), name="zamimg_proxy"),
    re_path(f"flower/(?P<path>.*)", flower_proxy_view, name="flower"),
    path("__debug__/", include("debug_toolbar.urls")),  # debug toolbar
]

if settings.DEBUG or not os.environ.get("RUN_FROM_DOCKER"):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += [
        re_path(f'^{settings.MEDIA_URL.lstrip("/")}(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),
        re_path(f'^{settings.STATIC_URL.lstrip("/")}(?P<path>.*)$', serve, {"document_root": settings.STATIC_ROOT}),
    ]

handler400 = "HomePage.views.bad_request"
handler403 = "HomePage.views.permission_denied"
handler404 = "HomePage.views.page_not_found"
handler500 = "HomePage.views.server_error"

mysite/user/urls.py
from django.urls import path

from user.views import *

app_name = "user"

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("registration/", RegistrationView.as_view(), name="registration"),
    path("terms-of-use/", TermsOfUseView.as_view(), name="terms-of-use"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("profile2/", profileView2, name="profile2"),
    path(
        "confirm-email/<str:uidb64>/<str:token>/<str:email>",
        UserConfirmEmailView.as_view(),
        name="confirm_email",
    ),
    path("email-confirmed/", EmailConfirmedView.as_view(), name="email_confirmed"),
    path(
        "confirm-email-failed/",
        EmailConfirmationFailedView.as_view(),
        name="email_confirmation_failed",
    ),
    path("reset-password/", UserResetPasswordView.as_view(), name="reset_password"),
    path(
        "reset-password2/",
        UserResetPasswordView2.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/<uidb64>/<token>/",
        PasswordResetConfirmCustomView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        PasswordResetCompleteCustomView.as_view(),
        name="password_reset_complete",
    ),
]

mysite/HomePage/views.py
import mimetypes
import uuid

from decouple import config
from django.conf import settings
from django.core.exceptions import BadRequest, PermissionDenied
from django.core.handlers.asgi import ASGIRequest
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import TemplateView
from proxy.views import proxy_view

from HomePage.tasks import send_problem_message

from common.mixin.views import TitleMixin


class HomePageView(TitleMixin, TemplateView):
    """Представление обрабатывающее главную страницу."""

    template_name = "HomePage/HomePage.html"
    title = "Главная страница"

    def get(self, request, *args, **kwargs):
        resp = super().get(request, *args, **kwargs)
        id_class = request.GET.get("class")

        if request.GET.get("data") == "talents":
            return HttpResponse(
                open(
                    f"./static/js/javascript/data-class={id_class}.js",
                    "r",
                    encoding="utf-8",
                ),
                content_type="application/x-javascript; charset=utf-8",
            )

        if request.GET.get("data") == "item-scaling":
            return HttpResponse(
                open(
                    "./static/js/javascript/data-item-scaling.js", "r", encoding="utf-8"
                ),
                content_type="application/x-javascript; charset=utf-8",
            )

        return resp

    def post(self, request: ASGIRequest, *args, **kwargs):
        if self.request.user.is_anonymous:
            return JsonResponse({"status": "access error"})

        if request.FILES:
            # Заполняем словарь нужными данными, так как селери не принимает файлы
            files = {}
            for file in request.FILES:
                files[request.FILES[file].name] = [
                    request.FILES[file].read(),
                    mimetypes.guess_type(request.FILES[file].name)[0],
                ]
        else:
            files = None

        text = request.POST.get("comment", "")

        if files or text != "":
            send_problem_message.delay(files, text)
            return JsonResponse({"status": "complaint sent successfully"})

        return JsonResponse({"status": "complaint not sent"})

    def render_to_response(self, context, **response_kwargs):
        response = super(HomePageView, self).render_to_response(
            context, **response_kwargs
        )

        if self.request.user.is_anonymous:
            if not self.request.COOKIES.get("userID"):
                response.set_cookie(
                    key="userID", value=uuid.uuid4(), domain=settings.PARENT_DOMAIN
                )

        if not self.request.COOKIES.get("ctrEnterWidget"):
            response.set_cookie(
                key="ctrEnterWidget", value="close", domain=settings.PARENT_DOMAIN
            )

        return response


def bad_request(request: ASGIRequest, exception: BadRequest) -> HttpResponse:
    """Обработка ошибки 400"""

    error_msg = "Сервер не смог распознать запрос."
    if type(exception) is BadRequest and str(exception):
        error_msg = str(exception)

    return render(
        request=request,
        template_name="error/error_page.html",
        status=400,
        context={"code": 400, "title": "Неверный запрос", "error_msg": error_msg},
    )


def permission_denied(request: ASGIRequest, exception: BadRequest) -> HttpResponse:
    """Обработка ошибки 403"""

    error_msg = "Доступ к данной странице запрещен."
    if type(exception) is BadRequest and str(exception):
        error_msg = str(exception)

    return render(
        request=request,
        template_name="error/error_page.html",
        status=403,
        context={"code": 403, "title": "Доступ запрещен", "error_msg": error_msg},
    )


def page_not_found(request: ASGIRequest, exception: BadRequest) -> HttpResponse:
    """Обработка ошибки 404"""

    error_msg = "Страница не существует или была перемещена на другой адрес."
    if type(exception) is BadRequest and str(exception):
        error_msg = str(exception)

    return render(
        request=request,
        template_name="error/error_page.html",
        status=404,
        context={"code": 404, "title": "Страница не найдена", "error_msg": error_msg},
    )


def server_error(request: ASGIRequest) -> HttpResponse:
    """Обработка ошибки 500"""

    error_msg = (
        "Cервер столкнулся с неожиданной ошибкой, администрация уже работает над этим."
    )

    return render(
        request=request,
        template_name="error/error_page.html",
        status=500,
        context={"code": 500, "title": "Ошибка сервера", "error_msg": error_msg},
    )


@csrf_exempt
def flower_proxy_view(request: ASGIRequest, path: str) -> HttpResponse:
    """Представление позволяющее открывать панель flower
    как обычную страницу django (только для супер пользователя)."""

    if not request.user.is_superuser:
        raise PermissionDenied
    return proxy_view(
        request,
        f"http://{config('CELERY_FLOWER_ADDRESS')}:{config('CELERY_FLOWER_PORT')}/{config('CELERY_FLOWER_URL_PREFIX')}/{path}",
        {},
    )

mysite/HomePage/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="ru" xmlns="http://www.w3.org/1999/html">
  <head>
    <meta charset="utf-8">
    <script src="{% static 'js/javascript/zamimg_power.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
     <script src="{% static 'js/javascript/wow-model-viewer/viewer_wrath.min.js' %}"></script>
    <script src="{% static 'js/javascript/wow-model-viewer/model_viewer_utils.js' %}"></script>

     <base href="http://127.0.0.1:8000/">
      <script>const whTooltips = {colorLinks: false, iconize: 'large', renameLinks: false};</script>

<!--    <base href="www.wowhead.com">-->
    <link rel="shortcut icon" href="#">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,200;0,400;0,600;1,200;1,300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">
<!--      <script src="https://pagination.js.org/dist/2.6.0/pagination.js"></script>-->

      <script src="https://cdn.jsdelivr.net/npm/gsap@3.12/dist/gsap.min.js"></script>

    <title>Kenunchik</title>

    <link rel="stylesheet" href="{% static 'style.css' %}">

    <style>
   /* main box settings */
.dropdown[_ngcontent-gox-c59] img[_ngcontent-gox-c59] {
height: 20px;
margin-right: 10px
}

/* color menu */
.dropdown-menu[_ngcontent-gox-c59] { /* полоска под дропдаун меню */
background-color: #000;
border-bottom: 2px solid #1fb8ff;
padding-bottom: 1px;
box-shadow: 0 0 30px 10px #ffffff12;
}

/* color pri hover */
.dropdown-menu[_ngcontent-gox-c59] .dropdown-item[_ngcontent-gox-c59] {
color: #fff;
cursor: Pointer;
padding: 0rem 0rem
}
.dropdown-menu[_ngcontent-gox-c59] .dropdown-item[_ngcontent-gox-c59]:hover {
background-color: #252525
}

/* ramka main box */
.btn-select-lang[_ngcontent-gox-c59] {
color: #fff;
border-color: #343a40;
background-color: #201e21;
padding: 2px 10px
}

/* pri navedenii na main box */
.btn-select-lang[_ngcontent-gox-c59]:hover {
background-color: #151515
}
#dropdownMenuButton[_ngcontent-gox-c59] img[_ngcontent-gox-c59],
.dropdown-menu[_ngcontent-gox-c59] .dropdown-item[_ngcontent-gox-c59] img[_ngcontent-gox-c59] {
vertical-align: sub
}

    /* settings btns v menu */
.russian-btn {
  border:none;
  width: 158px;
  height: 25px;
  background: url("{% static 'img/langue/RU.svg' %}") no-repeat 10px 2px;
  background-size: auto 85%;
  text-align: center;
  padding-left: 30px;
  color:#fff;
  font-family: 'Inter', sans-serif;
}
.english-btn {
  border:none;
  width: 158px;
  height: 25px;
  background: url("{% static 'img/langue/EN.svg' %}") no-repeat 10px 2px;
  background-size: auto 85%;
  text-align: center;
  padding-left: 30px;
  color:#fff;
  font-family: 'Inter', sans-serif;


}

    </style>

  </head>
<body>
    <div class='header'>
       <div class='header-line'>

         <div class='header-logo'>
           <p>ЛОГО</p>
         </div>

         <div class='nav'>

           <a class='nav-item' href="{% url 'home' %}">Главная</a>
           <a class='nav-item' href="{% url 'char' %}">Персонаж</a>
           <a class='nav-item' href="@">Таланты</a>
           <a class='nav-item' href="{% url 'addons:shop' %}">Аддоны</a>
           <a class='nav-item' href="@">Услуги</a>


         </div>



        <nav _ngcontent-gox-c59="" class="navbar navbar-expand-xl navbar-dark bg-navbar select-none">
          <div _ngcontent-gox-c59="" id="nav-menu" class="collapse navbar-collapse">
              {% if user.is_authenticated %}
                    <a class='nav-item' href="{% url 'user:login' %}" style="font-size: 18px;     margin-right: 10px;
    color: #fff;
    font-size: 16px;
    font-family: Inter;
    font-style: normal;
    font-weight: 400;
    line-height: normal;">{{ user }}</a>
              {% else %}
                    <a class='nav-item' href="{% url 'user:login' %}" style="font-size: 18px;    margin-right: 10px; color: #fff;font-size: 16px;font-family: Inter;font-style: normal;font-weight: 400;line-height: normal;">Войти</a>
              {% endif %}
            <div _ngcontent-gox-c59="" class="dropdown float-left d-none d-xl-inline">
              <button _ngcontent-gox-c59="" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="btn btn-select-lang dropdown-toggle">
                <img _ngcontent-gox-c59="" src="{% static 'img/langue/RU.svg' %}">
              </button>

              <div _ngcontent-gox-c59="" aria-labelledby="dropdownMenuButton" class="dropdown-menu">
                  <span _ngcontent-gox-c59="" class="dropdown-item">
                    <form action="https://frishub.ru/i18n/setlang/" method="POST">
                      <input type="hidden" name="csrfmiddlewaretoken" value="Ndcf8DyDe3PA6WdlG4NW1aEuhlZonnitVPlue1mbMKPgtBcbVQ1vkoDJRvtGDJHL">
                      <input _ngcontent-gox-c59="" class="russian-btn" type="hidden" name="language" value="ru">
                      <input _ngcontent-gox-c59="" class="russian-btn" value="Русский" type="button">
                    </form>
                  </span>

                  <span _ngcontent-gox-c59="" class="dropdown-item">
                    <form action="https://frishub.ru/i18n/setlang/" method="POST">
                      <input type="hidden" name="csrfmiddlewaretoken" value="Ndcf8DyDe3PA6WdlG4NW1aEuhlZonnitVPlue1mbMKPgtBcbVQ1vkoDJRvtGDJHL">
                      <input _ngcontent-gox-c59="" class="english-btn" type="hidden" name="language" value="en">
                      <input _ngcontent-gox-c59="" class="english-btn" value="English" type="submit">
                    </form>
                  </span>

              </div>
            </div>
          </div>
        </nav>


         </div>

       </div>

  {% block content %}

  {% endblock %}

  {% block footer %}

  {% endblock %}

</body>

{% block js %}

{% endblock %}

</html>

mysite/HomePage/templates/char.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>WoW model viewer</title>
<!--    <base href="http://subdomain.domain.com/subdirectory/">-->
<!--    <meta name="viewport" content="width=device-width, initial-scale=1">-->
<!--    <link rel="icon" type="image/x-icon" href="favicon.ico">-->
    <script crossorigin="anonymous" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="{% static 'js/javascript/zamimg_power.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
     <script src="{% static 'js/javascript/wow-model-viewer/viewer_wrath.min.js' %}"></script>
      <script src="https://wow.zamimg.com/js/tooltips.js"></script>
    <script src="{% static 'js/javascript/wow-model-viewer/model_viewer_utils.js' %}"></script>
    <link href="https://fonts.cdnfonts.com/css/lifecraft" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

<!--<link rel="stylesheet" href="//wow.zamimg.com/modelviewer/viewer/viewer.css" type="text/css"><link rel="stylesheet" href="//wow.zamimg.com/modelviewer/viewer/viewer.css" type="text/css"><link rel="stylesheet" href="//wow.zamimg.com/modelviewer/viewer/viewer.css" type="text/css"></head>-->
<body class="">
<h1>
    WoW model viewer
</h1>
<div class='model_3d' id="model_3d"></div>
<div>
    <div>
        <button onclick="randAnimation(window.model1)">Random animation</button>
    </div>
    <div>
        <button onclick="randAnimation(window.model3)">Arthas random animation</button>
    </div>
    <div>
        <button onclick="pauseAnimation()">Pause animation</button>
    </div>
    <div>
        <button onclick="fullScreen()">Full Screen</button>
    </div>
    <div>
        <button onclick="changeDirection()">Change rotation</button>
    </div>
    <div class="fullscrin">
        <button onclick="fullScreen()">Full Screen</button>
    </div>

    <div class="clearSlots">
        <button onclick="clearSlot(3)">Clear slots(3)</button>
    </div>

    <div class="setItems">
        <button onclick="setItems(3, 65197, 0)">setItem</button>
    </div>
</div>
<div>
    <a href="https://github.com/Miorey/wow-model-viewer">GitHub</a>
    <a href="https://www.npmjs.com/package/wow-model-viewer">npm</a>
</div>

<style>
    body {
        background: #333;
        color: #fff;
        font-family: 'Open Sans', sans-serif;
    }

    .model_3d {
        height: 1000px;
    }
    h1, h2, h3, h4, h5 {
        font-family: 'LifeCraft', sans-serif;
        color: #000;
        text-shadow: 0 0 2px #f9c811, 0 0 2px #f9c811, 0 0 2px #f9c811, 0 0 2px #f9c811;
        text-align: center;
    }

    h1 {
        bottom: 0;
        left: 58px;
    }
    button, a {
        color: #d3b359;
        text-shadow: -2px 0 #000, 0 2px #000, 1px 0 #000, 0 -2px #000;
        font-weight: bold;
        background: #7d0b0c;
        background: -webkit-radial-gradient(#7d0b0c 30%, #4e0c0b 60%);
        background: -o-radial-gradient(#7d0b0c 30%, #4e0c0b 60%);
        background: -moz-radial-gradient(#7d0b0c 30%, #4e0c0b 60%);
        background: radial-gradient(#7d0b0c 30%, #4e0c0b 60%);
        border: 2px solid #26160c;
        transition: text-shadow 0.5s, color 0.5s, border-color 0.5s, box-shadow 0.5s, background 0.5s;
        -webkit-transition: text-shadow 0.5s, color 0.5s, border-color 0.5s, box-shadow 0.5s, background 0.5s;
        -moz-transition: text-shadow 0.5s, color 0.5s, border-color 0.5s, box-shadow 0.5s, background 0.5s;
        -o-transition: text-shadow 0.5s, color 0.5s, border-color 0.5s, box-shadow 0.5s, background 0.5s;
        margin: 4px;
    }
    button:hover, a:hover {
        color: #f9c811;
        text-shadow: -2px 0 #000, 0 2px #000, 1px 0 #000, 0 -2px #000;
    }
    code {
        display: block;
        margin-top: 5px;
        margin-bottom: 5px;
    }
    a {
        text-decoration: none;
        display: inline-block;
        padding: 3px;
        font-size: 1.25em;
    }
</style>

<script type="module">

    const character = {
        "face": 1,
        "gender": 1,
        "generalOptions": {'mount': {"type": 8, "id": 0}},
        "hair_color": 0,
        "hair_style": 0,
        "items": [],
        "piercings": 0,
        "race": 1,
        "sheathMain": 8,
        "sheathOff": 9,
        "skin_color": 3

    };
    window.model = await generateModels('#model_3d', character);
    console.log(window.model)


</script>

</body>
</html>