mysite/mysite/urls.py
import os

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import include, path, re_path
from django.views.static import serve

from CharPage.views import *
from HomePage.views import *
from talants.views import *
from user.views import *


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", HomePageView.as_view(), name="home"),
    path("user/", include("user.urls", namespace="user")),
    path("support/", include("support.urls", namespace="support")),
    path("addons/", include("addons.urls", namespace="addons")),
    path("services/", include("services.urls", namespace="services")),
    path("char/", CharPageView.as_view(), name="char"),
    path("charlist/", CharListPageView.as_view(), name="char_list"),
    path("createchar/<uuid:room_id>/", CreateCharView.as_view(), name="createchar"),
    path("char/<uuid:room_id>/", UniqueCharPageView.as_view(), name="char_page_room"),
    path("talents/", TalantsView.as_view(), name="talants"),
    path("api/modelviewer/<path:modelviewer_path>/", ZamimgProxyView.as_view(), name="zamimg_proxy"),
    re_path(f"flower/(?P<path>.*)", flower_proxy_view, name="flower"),
    path("__debug__/", include("debug_toolbar.urls")),  # debug toolbar
]

if settings.DEBUG or not os.environ.get("RUN_FROM_DOCKER"):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += [
        re_path(f'^{settings.MEDIA_URL.lstrip("/")}(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),
        re_path(f'^{settings.STATIC_URL.lstrip("/")}(?P<path>.*)$', serve, {"document_root": settings.STATIC_ROOT}),
    ]

handler400 = "HomePage.views.bad_request"
handler403 = "HomePage.views.permission_denied"
handler404 = "HomePage.views.page_not_found"
handler500 = "HomePage.views.server_error"

mysite/user/urls.py
from django.urls import path

from user.views import *

app_name = "user"

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("registration/", RegistrationView.as_view(), name="registration"),
    path("terms-of-use/", TermsOfUseView.as_view(), name="terms-of-use"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("profile2/", profileView2, name="profile2"),
    path(
        "confirm-email/<str:uidb64>/<str:token>/<str:email>",
        UserConfirmEmailView.as_view(),
        name="confirm_email",
    ),
    path("email-confirmed/", EmailConfirmedView.as_view(), name="email_confirmed"),
    path(
        "confirm-email-failed/",
        EmailConfirmationFailedView.as_view(),
        name="email_confirmation_failed",
    ),
    path("reset-password/", UserResetPasswordView.as_view(), name="reset_password"),
    path(
        "reset-password2/",
        UserResetPasswordView2.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/<uidb64>/<token>/",
        PasswordResetConfirmCustomView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        PasswordResetCompleteCustomView.as_view(),
        name="password_reset_complete",
    ),
]

mysite/user/models.py
from django.core.cache import cache
from django.db import models

from django.contrib.auth.models import AbstractUser
from django.utils import timezone


# Create your models here.


class User(AbstractUser):
    discord = models.CharField(max_length=32, null=True, verbose_name="Discord")

    def is_online(self) -> bool:
        last_seen = cache.get(f"last-seen-{self.id}")
        if last_seen is not None and timezone.now() < last_seen + timezone.timedelta(
            seconds=300
        ):
            return True
        return False

mysite/user/views.py
import json
from datetime import timedelta

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login, update_session_auth_hash
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetView,
)
from django.contrib.messages.views import SuccessMessageMixin
from django.core.handlers.asgi import ASGIRequest
from django.http import JsonResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.views.generic.base import TemplateView, View
from django.views.generic.edit import CreateView

from common.mixin.views import TitleMixin
from services.models import ServicesModel
from user.forms import PasswordChangeForm, PasswordResetCustomForm, UserLoginForm, UserRegistrationForm
from user.models import User
from user.tasks import send_update_email_message
from user.utils import RedirectAuthUser


class RegistrationView(TitleMixin, RedirectAuthUser, SuccessMessageMixin, CreateView):
    """Представление обрабатывающее страницу регистрации пользователя."""

    model = User
    form_class = UserRegistrationForm
    template_name = "registration.html"
    success_url = reverse_lazy("user:login")
    success_message = "Вы успешно зарегистрировались!"
    redirect_auth_user_url = "user:profile"
    title = "Регистрация"

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        username = form.cleaned_data.get("username")
        messages.success(self.request, f"Добро пожаловать {username}.")
        return redirect("home")


class TermsOfUseView(TitleMixin, TemplateView):
    """Представление обрабатывающее страницу с политикой конфиденциальности."""

    template_name = "terms_of_use.html"
    title = "Политика конфиденциальности"


class UserLoginView(TitleMixin, RedirectAuthUser, LoginView):
    """Представление обрабатывающее страницу входа в аккаунт."""

    template_name = "login.html"
    form_class = UserLoginForm
    redirect_auth_user_url = "user:profile"
    title = "Вход"

    def get_success_url(self):
        messages.success(self.request, f"Добро пожаловать {self.request.user.get_username()}.")
        return reverse_lazy("home")

    def form_valid(self, form):
        remember_me = form.cleaned_data.get("remember_me")
        if not remember_me:
            self.request.session.set_expiry(0)
        return super(UserLoginView, self).form_valid(form)


class UserLogoutView(LoginRequiredMixin, LogoutView):
    """Представление обрабатывающее выход пользователя из аккаунта."""

    permission_denied_message = "Вы не авторизованы."
    raise_exception = True

    def get(self, request: ASGIRequest, *args, **kwargs):
        self.username = request.user.get_username()

        return super().get(request, *args, **kwargs)

    def get_success_url(self):
        messages.success(self.request, f"До скорых встреч {self.username}")
        return reverse_lazy("home")


class UserResetPasswordView(TitleMixin, RedirectAuthUser, PasswordResetView):
    """Представление обрабатывающее страницу сброса пароля."""

    template_name = "reset_password.html"
    form_class = PasswordResetCustomForm
    email_template_name = "emails/password_reset_email.html"
    html_email_template_name = "emails/password_reset_email.html"
    redirect_auth_user_url = "user:profile"
    title = "Сброс пароля"

    def get_success_url(self):
        messages.success(self.request, "Письмо успешно отправлено.")
        return reverse_lazy("user:password_reset_confirm")

    def render_to_response(self, context, **response_kwargs):
        if self.request.COOKIES.get("reset_password"):
            messages.warning(self.request, "Пароль можно сбросить раз в 15 минут.")
            return redirect("user:login")
        return super(UserResetPasswordView, self).render_to_response(context, **response_kwargs)


class UserResetPasswordView2(RedirectAuthUser, TemplateView):
    """Представление обрабатывающее страницу успешной отправки ссылки на почту для сброса пароля"""

    template_name = "reset_password_sended.html"
    redirect_auth_user_url = "user:profile"


class PasswordResetConfirmCustomView(TitleMixin, RedirectAuthUser, PasswordResetConfirmView):
    """#### Представление обрабатывающее страницу с формой для ввода нового пароля."""

    form_class = SetPasswordForm
    redirect_auth_user_url = "user:profile"
    template_name = "password_reset_confirm.html"
    title = "Сброс пароля"

    # автоматическая аутентификация пользователя после успешного сброса пароля
    # post_reset_login = True

    def get_success_url(self):
        messages.success(self.request, "Новый пароль успешно сохранён!")
        return reverse_lazy("user:password_reset_complete")


class PasswordResetCompleteCustomView(TitleMixin, RedirectAuthUser, PasswordResetCompleteView):
    """#### Представление обрабатывающее страницу с сообщением об успешной смене пароля."""

    redirect_auth_user_url = "user:profile"

    template_name = "reset_password_complete.html"
    title = "Успех!"

    def render_to_response(self, context, **response_kwargs):
        response = super(PasswordResetCompleteCustomView, self).render_to_response(context, **response_kwargs)
        time_delta = timedelta(minutes=15)
        response.set_cookie(
            key="reset_password",
            value=timezone.now(),
            expires=timezone.now() + time_delta,
            domain=settings.PARENT_DOMAIN,
        )
        return response


class ProfileView(TitleMixin, LoginRequiredMixin, TemplateView):
    """Представление обрабатывающее страницу профиля пользователя."""

    template_name = "profile.html"
    login_url = reverse_lazy("user:login")
    title = "Личный кабинет"

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)

        if self.request.session.get("PasswordChangeForm-errors"):
            context["PasswordChangeFormerrors"] = json.loads(self.request.session.get("PasswordChangeForm-errors", ""))
            del self.request.session["PasswordChangeForm-errors"]
        else:
            context["PasswordChangeFormerrors"] = ""

        context["PasswordChangeForm"] = PasswordChangeForm(self.request.GET or None)
        context["user_services"] = list(reversed(ServicesModel.objects.filter(creator=self.request.user)))

        return context

    def post(self, request: ASGIRequest, *args, **kwargs):
        data: dict = json.loads(request.body)

        if data.get("update_discord"):
            user = self.request.user
            user.discord = data["update_discord"]
            user.save()
            return JsonResponse({"status": "data was successfully discrod updated"})

        if data.get("update_email"):
            user = self.request.user
            token = default_token_generator.make_token(user)
            uid = urlsafe_base64_encode(force_bytes(user.pk))
            email = urlsafe_base64_encode(force_bytes(data["update_email"]))

            if User.objects.filter(email=data["update_email"]).exists():
                return JsonResponse({"status": "the specified mailing address is already in use"})

            activation_url = reverse_lazy(
                "user:confirm_email",
                kwargs={"uidb64": uid, "token": token, "email": email},
            )
            # current_site = Site.objects.get_current().domain
            current_site = "127.0.0.1:8000"
            send_update_email_message.delay(user.email, current_site, activation_url)
            return JsonResponse({"status": "email details were successfully updated"})


def profileView2(request):
    user = request.user

    if request.method == "POST":
        change_form = PasswordChangeForm(user, request.POST)
        if change_form.is_valid():
            old_password = change_form.cleaned_data["old_password"]
            change_form.save()
            update_session_auth_hash(request, change_form.user)
            messages.success(request, "Вы успешно изменили пароль")
            return redirect(reverse_lazy("user:profile"))
        else:
            change_form_errors = json.dumps(change_form.errors, default=str)
            request.session["PasswordChangeForm-errors"] = change_form_errors
        return redirect(reverse_lazy("user:profile"))


class UserConfirmEmailView(View):
    def get(self, request, uidb64, token, email):
        try:
            uid = urlsafe_base64_decode(uidb64)
            user = User.objects.get(pk=uid)
            email = urlsafe_base64_decode(email)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            user.email = email.decode("utf-8")
            user.save()
            return redirect("user:email_confirmed")
        else:
            return redirect("user:email_confirmation_failed")


class EmailConfirmedView(TitleMixin, TemplateView):
    """Представление обрабатывающее страницу успешной смены почтового ящика"""

    template_name = "email_confirmed.html"
    title = "Успех!"


class EmailConfirmationFailedView(TitleMixin, TemplateView):
    """Представление обрабатывающее страницу не успешного сброса почтового ящика"""

    template_name = "email_confirmed_failed.html"
    title = "Упс!!"

mysite/user/templates/email_confirmed.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
Почта изменена
{% endblock %}

mysite/user/templates/email_confirmed_failed.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'email-confirmed.css' %}">
{% endblock %}

{% block content %}
<div class="confirmed_email">
    <p>Почта не изменена!</p>
</div>
{% endblock %}

mysite/user/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="login-block">

    <div class="create-acc-text">

        <p>Вход в аккаунт</p>

    </div>

    <div class="input-block">
    <form action="{% url 'user:login' %}" method="post">
        {% csrf_token %}
    <div class="login-input" id="login-input">

        <p id="placeholder-login">Логин</p>
        {{ form.username }}

    </div>
    <div class="password-input" id="password-input">

        <p id="placeholder-password">Пароль</p>
        {{ form.password }}

    </div>

    </div>

    <div class="forgot-pass">

        <div class="remember-me">

            {{ form.remember_me }}
            <p>Запомнить меня</p>

        </div>

        <a href="{% url 'user:reset_password' %}">Забыли пароль?</a>

    </div>

    <div class="btn-login" >

        <button type="submit" value="Войти">Войти</button>

    </div>
    <div class="registration">

        <p>Нет аккаунта?</p>
        <a href="{% url 'user:registration' %}">Зарегистрироваться</a>

    </div>

    </form>
</div>

{% endblock %}

{% block js %}
<script>
    // input anim...............................................................................................

        function inputcheck(textid, input) {
            var text = document.getElementById(`${textid}`);
            let coords = {top: text.offsetTop, left: text.offsetLeft};
            console.log(coords);

            var top = text.offsetTop;
            var left = text.offsetLeft;

            console.log(text.offsetLeft, text.offsetTop);
            var fsize = 16;
            if(window.getComputedStyle(text, null).fontSize == fsize + "px"){

            var topy = setInterval(topfunc, 10);
            var leftx = setInterval(leftfunc, 23);
            var fsizex = setInterval(fsizefunc, 23);
            function topfunc() {
                var direction = 1;
                if(top == coords.top - 25) {
                    clearInterval(topy);
                }else {
                    console.log(1);
                    top -= 1 * direction;
                    text.style.top = top + "px";
                }
                }

            function leftfunc() {
                var direction = 1;
                if(left == coords.left - 5) {
                    clearInterval(leftx);
                }else {
                     left -= 1 * direction;
                    text.style.left = left + "px";
                }
                }

            function fsizefunc() {
                var bttn = document.getElementById(`${input}`);
                var direction = 1;
                if(fsize == 13) {
                    bttn.disabled = false;
                    clearInterval(fsizex);
                }else {
                    fsize -= 1 * direction;
                    text.style.fontSize = fsize + "px";
                }
                }
                }
        }

        function inputout(idtext, input) {
            var text = document.getElementById(`${idtext}`);

            //console.log(document.getElementById(`${input}`).value) //--- чтение из инпута
            if(document.getElementById(`${input}`).value == ""){

            let coords = {top: text.offsetTop, left: text.offsetLeft};
            //console.log(coords);

            var top = text.offsetTop;
            var left = text.offsetLeft;

            //console.log(text.offsetLeft, text.offsetTop);
            var fsize = 13;
            if(window.getComputedStyle(text, null).fontSize == fsize + "px"){


            var topy = setInterval(topfunc, 10);
            var leftx = setInterval(leftfunc, 23);
            var fsizex = setInterval(fsizefunc, 25);

                function topfunc() {
                    var direction = -1;
                    if(top == coords.top + 25) {
                        clearInterval(topy);
                    }else {
                        top -= 1 * direction;
                        text.style.top = top + "px";
                    }
                    }

                function leftfunc() {
                    var direction = -1;
                    if(left == coords.left + 5) {
                        clearInterval(leftx);
                    }else {
                         left -= 1 * direction;
                        text.style.left = left + "px";
                    }
                    }

                function fsizefunc() {
                    var bttn = document.getElementById(`${input}`);
                    var direction = -1;
                    if(fsize == 16) {
                        bttn.disabled = false;
                        clearInterval(fsizex);
                    }else {
                        bttn.disabled = true;
                        fsize -= 1 * direction;
                        text.style.fontSize = fsize + "px";
                    }
                    }
                    }
            }


        }
        // вызов функции на нажатие инпут
        document.getElementById("input-login").addEventListener('mousedown', inputcheck.bind(null, "placeholder-login", "input-login"));
        document.getElementById("input-login").addEventListener('focus', inputcheck.bind(null, "placeholder-login", "input-login"));
        document.getElementById("input-password").addEventListener('mousedown', inputcheck.bind(null, "placeholder-password", "input-password"));
        document.getElementById("input-password").addEventListener('focus', inputcheck.bind(null, "placeholder-password", "input-password"));

        // вызов функции при ухода из инпута
        document.getElementById("input-login").addEventListener('focusout', inputout.bind(null, "placeholder-login", "input-login"));
        document.getElementById("input-password").addEventListener('focusout', inputout.bind(null, "placeholder-password", "input-password"));

//................................................................................................................................................


</script>

{% endblock %}

mysite/user/templates/password_reset_confirm.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'reset_password.css' %}">
{% endblock %}

{% block content %}
<form method="POST">
  {% csrf_token %}
<div class="set_new_password_block">
  {% if validlink %}
  <div class="set_new_password_header">
    <p>Придумайте новый пароль</p>
  </div>
  <div class="set_new_password_main">
    <div class="set_new_password_inputs_desc">
      <p>Введите новый пароль</p>
      <p>Подтвердите пароль</p>
    </div>
    <div class="set_new_password_inputs">
    {{ form.new_password1 }}
    {{ form.new_password2 }}
      </div>
  </div>
  <div class="set_new_password_footer">
    <div class="button_set_new_password">
    <button type="submit" value="Сбросить пароль">Изменить пароль</button>
      </div>
  </div>
  {% else %}
  <p class="invalid-link">Ссылка недействительная, скорее всего она уже использовалась. Попробуйте запросить сброс пароля еще раз.</p>
  {% endif %}
</div>
</form>
{% endblock %}

mysite/user/templates/registration.html
{% extends 'base.html' %}
{% load static %}

{% block header %}

{% endblock %}

{% block content %}

<div class="register-block">

    <div class="create-acc-text">

        <p>Создание аккаунта</p>

    </div>

    <div class="input-block">
    <form action="{% url 'user:registration' %}" method="post" >
        {% csrf_token %}
    <div class="login-input" id="login-input">

        <p id="placeholder-login">Логин</p>
        {{ form.username }}

    </div>
    <div class="password-input" id="password-input">

        <p id="placeholder-password">Пароль</p>
        {{ form.password1 }}

    </div>
    <div class="repeat-password-input" id="repeat-password-input">

        <p id="placeholder-repeat-password">Подтвердите пароль</p>
        {{ form.password2 }}

    </div>
    <div class="email-input" id="email-input">

        <p id="placeholder-email">Почта</p>
        {{ form.email }}

    </div>
<!--        {{ form.errors }}-->
            <script type="text/javascript">
        function flash_captcha(){
            var state = 'show'
            // повторить с интервалом .2 секунды
            let timerId = setInterval(() => {
                if(state == 'show'){
                    document.querySelector('#RecaptchaField1').style.opacity = 0
                    state = 'hide'
                }
                else {
                   document.querySelector('#RecaptchaField1').style.opacity = 1
                    state = 'show'
                }
            }, 200);

            // остановить вывод через 1.2  секунд
            setTimeout(() => clearInterval(timerId), 1200);
        }
        var verifyCallback = function(response) {
            console.log('captchacallback')
            var captcha = grecaptcha.getResponse()
            var button = document.querySelector('.button_register')
            if (captcha.length){
                button.setAttribute('type', 'submit');
                button.setAttribute('onclick', '');
            }
      };
//        var onloadCallback = function() {
//       grecaptcha.render(document.getElementById('RecaptchaField1'), {
//          'sitekey' : '6LdV7zIpAAAAAGbJFz3JWZ9cIrQNJbh6NDF1Oj2t',
//          'callback' : verifyCallback,
//          'theme' : 'light'
//        });
//    alert("grecaptcha is ready!");
//  };

//        var onloadCallback = function() {
//
//    if ( $('#RecaptchaField1').length ) {
//        grecaptcha.render('RecaptchaField1', {
//            'sitekey' : '6LdV7zIpAAAAAGbJFz3JWZ9cIrQNJbh6NDF1Oj2t',
//            'theme': 'light',
//            'callback': 'verifyCallback'
//        });
//    }
//};
</script>

        {{ form.captcha }}

        <div class="terms_of_use">
        {{ form.terms_of_use }}
            <p>Я соглашаюсь с <a href="{% url 'user:terms-of-use' %}">Политикой конфиденциальности</a></p>
        </div>
    </div>

<!--    <div class="captcha-block">-->

<!--        <p>reCAPTCHA</p>-->

<!--    </div>-->



<!--        <script src='https://www.google.com/recaptcha/api.js'></script>-->
<!--        <div class="g-recaptcha" id="RecaptchaField1" data-sitekey="6LdV7zIpAAAAAGbJFz3JWZ9cIrQNJbh6NDF1Oj2t" render="explicit" data-theme="light" style="margin: 0px 25px 26px 25px;"></div>-->

<!--        <div id="RecaptchaField1" style="margin: 0px 25px 26px 25px;"></div>-->

        <div class="btn-registration">

        <button type="button" class="button_register" onclick="flash_captcha()">Регистрация</button>

        </div>



    </form>
<!--<script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit"-->
<!--        async defer>-->
    </script>
    <div class="href-login">
        <p>Уже есть аккаунт?</p>
        <a href="{% url 'user:login' %}">Войти</a>
    </div>

</div>

{% endblock %}

{% block js %}
<script type="module">


    // input anim...............................................................................................

        function inputcheck(textid, input) {
            var text = document.getElementById(`${textid}`);
            let coords = {top: text.offsetTop, left: text.offsetLeft};
            console.log(coords);

            var top = text.offsetTop;
            var left = text.offsetLeft;

            console.log(text.offsetLeft, text.offsetTop);
            var fsize = 16;
            if(window.getComputedStyle(text, null).fontSize == fsize + "px"){

            var topy = setInterval(topfunc, 10);
            var leftx = setInterval(leftfunc, 23);
            var fsizex = setInterval(fsizefunc, 23);
            function topfunc() {
                var direction = 1;
                if(top == coords.top - 25) {
                    clearInterval(topy);
                }else {
                    console.log(1);
                    top -= 1 * direction;
                    text.style.top = top + "px";
                }
                }

            function leftfunc() {
                var direction = 1;
                if(left == coords.left - 5) {
                    clearInterval(leftx);
                }else {
                     left -= 1 * direction;
                    text.style.left = left + "px";
                }
                }

            function fsizefunc() {
                var bttn = document.getElementById(`${input}`);
                var direction = 1;
                if(fsize == 13) {
                    bttn.disabled = false;
                    clearInterval(fsizex);
                }else {
                    fsize -= 1 * direction;
                    text.style.fontSize = fsize + "px";
                }
                }
                }
        }

        function inputout(idtext, input) {
            var text = document.getElementById(`${idtext}`);

            //console.log(document.getElementById(`${input}`).value) //--- чтение из инпута
            if(document.getElementById(`${input}`).value == ""){

            let coords = {top: text.offsetTop, left: text.offsetLeft};
            //console.log(coords);

            var top = text.offsetTop;
            var left = text.offsetLeft;

            //console.log(text.offsetLeft, text.offsetTop);
            var fsize = 13;
            if(window.getComputedStyle(text, null).fontSize == fsize + "px"){


            var topy = setInterval(topfunc, 10);
            var leftx = setInterval(leftfunc, 23);
            var fsizex = setInterval(fsizefunc, 25);

                function topfunc() {
                    var direction = -1;
                    if(top == coords.top + 25) {
                        clearInterval(topy);
                    }else {
                        top -= 1 * direction;
                        text.style.top = top + "px";
                    }
                    }

                function leftfunc() {
                    var direction = -1;
                    if(left == coords.left + 5) {
                        clearInterval(leftx);
                    }else {
                         left -= 1 * direction;
                        text.style.left = left + "px";
                    }
                    }

                function fsizefunc() {
                    var bttn = document.getElementById(`${input}`);
                    var direction = -1;
                    if(fsize == 16) {
                        bttn.disabled = false;
                        clearInterval(fsizex);
                    }else {
                        bttn.disabled = true;
                        fsize -= 1 * direction;
                        text.style.fontSize = fsize + "px";
                    }
                    }
                    }
            }


        }

        // вызов функции на нажатие инпут
        document.getElementById("input-login").addEventListener('mousedown', inputcheck.bind(null, "placeholder-login", "input-login"));
        document.getElementById("input-login").addEventListener('focus', inputcheck.bind(null, "placeholder-login", "input-login"));
        document.getElementById("input-password").addEventListener('mousedown', inputcheck.bind(null, "placeholder-password", "input-password"));
        document.getElementById("input-password").addEventListener('focus', inputcheck.bind(null, "placeholder-password", "input-password"));
        document.getElementById("input-repeat-password").addEventListener('mousedown', inputcheck.bind(null, "placeholder-repeat-password", "input-repeat-password"));
        document.getElementById("input-repeat-password").addEventListener('focus', inputcheck.bind(null, "placeholder-repeat-password", "input-repeat-password"));
        document.getElementById("input-email").addEventListener('mousedown', inputcheck.bind(null, "placeholder-email", "input-email"));
        document.getElementById("input-email").addEventListener('focus', inputcheck.bind(null, "placeholder-email", "input-email"));


        // вызов функции при ухода из инпута
        document.getElementById("input-login").addEventListener('focusout', inputout.bind(null, "placeholder-login", "input-login"));
        document.getElementById("input-password").addEventListener('focusout', inputout.bind(null, "placeholder-password", "input-password"));
        document.getElementById("input-repeat-password").addEventListener('focusout', inputout.bind(null, "placeholder-repeat-password", "input-repeat-password"));
        document.getElementById("input-email").addEventListener('focusout', inputout.bind(null, "placeholder-email", "input-email"));

//................................................................................................................................................


</script>

{% endblock %}

mysite/user/templates/reset_password.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'reset_password.css' %}">
{% endblock %}

{% block content %}
<form method="POST" action="{% url 'user:reset_password' %}">
    {% csrf_token %}
<div class="forgot_pass_block">
    <div class="forgot_pass_header">
        <p>Восстановление пароля</p>
    </div>
    <div class="forgot_pass_main">
        <p>Введите электронную почту связанную с аккаунтом. Вы получите письмо на указанную почту с дальнейшими указаниями.</p>
        <div class="forgot_pass_email">
<!--            <input type="email" id="forgot_pass_input" placeholder="">-->
        {{ form.email }}
        </div>
    </div>
    <div class="forgot_pass_footer">
        <div class="button_forgot_pass">
            <button type="submit" value="Сбросить пароль">Сбросить пароль</button>
        </div>
    </div>

</div>
    </form>
{% endblock %}

{% block js %}
<script>

</script>
{% endblock %}